version: "3.8"
services:
  dev_db:
    image: postgres:12.2-alpine
    env_file:
      - server/.env
    ports:
      - 5432:5432
    volumes:
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init.sql
